version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.1-sdk
    steps:
      - checkout
      - run: find .
      - run: dotnet restore ./src
      - run: dotnet build ./src
  test:
    docker:
      - image: microsoft/dotnet:2.1-sdk
    steps:
      - checkout
      - run: find .
      - run: dotnet restore ./test
      - run: dotnet test ./test --filter TestCategory!=IgnoreOnBuild --results-directory ./test/output
      - store_test_results:
          path: ./test/output
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
