version: 2
jobs:
  build:
    docker:
      - image: microsoft/aspnetcore-build:latest
    steps:
      - checkout:
          path: ./src
      - run: find .
      - run: dotnet restore
      - run: dotnet build
  test:
    docker:
      - image: microsoft/aspnetcore-build:latest
    steps:
      - checkout:
          path: ./test
      - run: find .
      - run: dotnet restore
      - run: dotnet test --filter TestCategory!=IgnoreOnBuild
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
