version: 2
jobs:
  build:
    working_directory: ./service-text-analysis/src
    docker:
      - image: microsoft/aspnetcore-build:latest
    steps:
      - checkout
      - run: find .
      - run: dotnet restore
      - run: dotnet build
  test:
    working_directory: ./service-text-analysis/test
    docker:
      - image: microsoft/aspnetcore-build:latest
    steps:
      - checkout
      - run: find .
      - run: dotnet restore
      - run: dotnet test --filter TestCategory!=IgnoreOnBuild
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
