version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.1-sdk
    steps:
      - checkout
      - run: find .
      - run: dotnet restore ./src
      - run: dotnet build ./src
  test:
    docker:
      - image: microsoft/dotnet:2.1-sdk
    steps:
      - checkout
      - run: find .
      - run: dotnet restore ./test
      - run: dotnet test ./test --filter TestCategory!=IgnoreOnBuild --logger "trx;LogFileName=testResults.xml" --results-directory ./output
      - store_artifacts:
          path: ./test/output
      - store_test_results:
          path: ./test/output
  deploy:
    docker:
      - image: microsoft/dotnet:2.1-sdk
    steps:
      - run:
          name: Publish to Elastic Beanstalk
          command: dotnet eb deploy-environment --publish-options "--runtime win-x64"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
